### ISSUE TITLE
Can I ask to share codes of VCP-CLIP?

### ISSUE THREAD

**Issue by YeongHyeon** [xiaozhen228/VCP-CLIP#2]
Hi,
Thank you for opening this repository,

I think that you are preparing the source code for sharing.
Can I ask the schedule of code update?
I will try your code for planning my future research.

**Comment by hongge831** [comment]
@xiaozhen228 +1

**Comment by syl0107** [comment]
@xiaozhen228 +1+1

**Comment by xiaozhen228** [comment]
Thanks for your attention. Our code will be released before August 20th.

**Comment by YeongHyeon** [comment]
Thank you for informing!

**Comment by IceIce1ce** [comment]
+1

**Comment by YangParky** [comment]
@xiaozhen228 +1，Is it suitable now ?
